"""Create listings, extractions, conflicts, traces, and saved searches

Revision ID: 2b820831cc90
Revises:
Create Date: 2026-09-20 20:25:41.673184

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b820831cc90"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=True),
        sa.Column("org_name", sa.Text(), nullable=True),
        sa.Column("species", sa.String(length=16), nullable=True),
        sa.Column("breed_primary", sa.Text(), nullable=True),
        sa.Column("breed_mixed", sa.Boolean(), nullable=True),
        sa.Column("sex", sa.String(length=16), nullable=True),
        sa.Column("age_bucket", sa.String(length=16), nullable=True),
        sa.Column("size_bucket", sa.String(length=16), nullable=True),
        sa.Column("weight_lb_listed", sa.Float(), nullable=True),
        sa.Column(
            "photos", postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), "sqlite"), nullable=True
        ),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("description_raw", sa.Text(), nullable=True),
        sa.Column("description_source", sa.Text(), nullable=True),
        sa.Column("description_hash", sa.String(length=64), nullable=True),
        sa.Column("normalization_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "structured_attrs",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_id", name="uq_listings_source_source_id"),
    )
    op.create_index("ix_listings_active", "listings", ["removed_at"], unique=False)
    op.create_index("ix_listings_hash", "listings", ["description_hash"], unique=False)
    op.create_index("ix_listings_species", "listings", ["species"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="running", nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=True),
        sa.Column("previous_active_count", sa.Integer(), nullable=True),
        sa.Column("soft_deleted_count", sa.Integer(), nullable=True),
        sa.Column("softdelete_skipped_reason", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_runs_kind_started", "pipeline_runs", ["kind", "started_at"], unique=False)
    op.create_table(
        "saved_searches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("radius_mi", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_saved_active", "saved_searches", ["active"], unique=False)
    op.create_table(
        "attribute_conflicts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("structured_value", sa.Text(), nullable=True),
        sa.Column("extracted_value", sa.String(length=32), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column(
            "offsets",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_conflicts_field", "attribute_conflicts", ["field"], unique=False)
    op.create_table(
        "extractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("extraction_version", sa.Integer(), nullable=False),
        sa.Column("model_used", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column(
            "fields",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("escalated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_id",
            "extraction_version",
            "prompt_version",
            name="uq_extractions_listing_version",
        ),
    )
    op.create_index(
        "ix_extractions_fields_gin",
        "extractions",
        ["fields"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"fields": "jsonb_path_ops"},
    )
    op.create_index("ix_extractions_listing", "extractions", ["listing_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("saved_search_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("channel", sa.String(length=16), server_default="email", nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["saved_search_id"],
            ["saved_searches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("saved_search_id", "listing_id", name="uq_notification_once"),
    )
    op.create_table(
        "pipeline_stage_traces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_traces_run_stage", "pipeline_stage_traces", ["run_id", "stage"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_traces_run_stage", table_name="pipeline_stage_traces")
    op.drop_table("pipeline_stage_traces")
    op.drop_table("notifications")
    op.drop_index("ix_extractions_listing", table_name="extractions")
    op.drop_index(
        "ix_extractions_fields_gin",
        table_name="extractions",
        postgresql_using="gin",
        postgresql_ops={"fields": "jsonb_path_ops"},
    )
    op.drop_table("extractions")
    op.drop_index("ix_conflicts_field", table_name="attribute_conflicts")
    op.drop_table("attribute_conflicts")
    op.drop_index("ix_saved_active", table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_index("ix_runs_kind_started", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index("ix_listings_species", table_name="listings")
    op.drop_index("ix_listings_hash", table_name="listings")
    op.drop_index("ix_listings_active", table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
