"""Consumer (c): the generated half of `evals/CODEBOOK.md`.

Labeling discipline requires one written definition per field value, fixed before any
labeling starts. Keeping those definitions in `pawsible.schema.enums` next to the values
themselves -- rather than in a prose file that drifts -- means the labeler, the prompt,
and the eval all read the same words. CI regenerates this and fails on a diff.

Per-member docstrings are not retained at runtime (PEP 224 was rejected), so they are
recovered by parsing the source. That is the price of keeping the definition adjacent
to the value it defines, and it is worth paying.
"""

from __future__ import annotations

import ast
import inspect
from enum import StrEnum
from pathlib import Path

from pawsible.schema import enums as enums_module
from pawsible.schema.fields import ExtractedFields

__all__ = ["member_docs", "render"]

# Which enum backs each field, and whether the field is multi-label.
_FIELD_ENUMS: dict[str, tuple[str, bool]] = {
    "good_with_cats": ("Compatibility", False),
    "good_with_dogs": ("Compatibility", False),
    "good_with_kids": ("Compatibility", False),
    "energy_level": ("EnergyLevel", False),
    "house_trained": ("TrainingState", False),
    "crate_trained": ("TrainingState", False),
    "placement": ("Placement", False),
    "separation_tolerance": ("SeparationTolerance", False),
    "home_requirements": ("HomeRequirement", True),
}


def member_docs(enum_name: str) -> dict[str, str]:
    """Return {member: docstring} by reading the source of `pawsible.schema.enums`."""
    tree = ast.parse(inspect.getsource(enums_module))
    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or node.name != enum_name:
            continue
        docs: dict[str, str] = {}
        pending: str | None = None
        for stmt in node.body:
            if isinstance(stmt, ast.Assign) and isinstance(stmt.targets[0], ast.Name):
                pending = stmt.targets[0].id
            elif (
                isinstance(stmt, ast.Expr)
                and isinstance(stmt.value, ast.Constant)
                and isinstance(stmt.value.value, str)
                and pending is not None
            ):
                docs[pending] = " ".join(stmt.value.value.split())
                pending = None
        return docs
    raise KeyError(enum_name)


def render() -> str:
    """Render the generated section. Deterministic; `make codebook` writes it to disk."""
    lines = [
        "<!-- GENERATED by pawsible.schema.codebook -- do not edit by hand. -->",
        "<!-- Edit the docstrings in pawsible/schema/enums.py and run `make codebook`. -->",
        "",
        "## Field vocabularies",
        "",
        "A field is left **UNKNOWN** by omitting it. UNKNOWN is not a value and never",
        "carries evidence: it means the description made no assertion either way.",
        "`NOT_TESTED` is the opposite -- an explicit statement in the text, with a span.",
        "",
    ]
    for field, (enum_name, multi) in _FIELD_ENUMS.items():
        enum_cls: type[StrEnum] = getattr(enums_module, enum_name)
        docs = member_docs(enum_name)
        label = "multi-label" if multi else "single value"
        lines += [
            f"### `{field}`",
            "",
            f"*{label}, drawn from `{enum_name}`*",
            "",
            "| Value | Definition |",
            "| --- | --- |",
        ]
        lines += [f"| `{m.value}` | {docs.get(m.name, '')} |" for m in enum_cls]
        lines.append("")

    lines += [
        "### `medical_needs[]`, `behavioral_notes[]`",
        "",
        "Each entry is `{summary, verbatim, offsets, ongoing_care}`. `verbatim` is what",
        "an adopter sees; `summary` exists only to make the entry filterable and is",
        "never shown as the claim. Never paraphrase a medical or behavioral statement.",
        "",
        "`ongoing_care` is true when the text describes care the adopter must continue",
        "-- daily medication, a prescription diet, a scheduled surgery -- and false for",
        "a resolved or historical condition.",
        "",
        "### Fields in the schema",
        "",
        "| Field | Required span |",
        "| --- | --- |",
    ]
    lines += [f"| `{name}` | yes |" for name in ExtractedFields.model_fields]
    lines.append("")
    return "\n".join(lines)


BEGIN_MARKER = "<!-- BEGIN GENERATED -->"
END_MARKER = "<!-- END GENERATED -->"


def splice(document: str) -> str:
    """Replace the generated block inside `document`, leaving the prose untouched."""
    start = document.index(BEGIN_MARKER) + len(BEGIN_MARKER)
    end = document.index(END_MARKER)
    return document[:start] + "\n\n" + render() + "\n" + document[end:]


if __name__ == "__main__":
    import sys

    target = Path(__file__).resolve().parents[2] / "evals" / "CODEBOOK.md"
    if "--write" in sys.argv:
        target.write_text(splice(target.read_text(encoding="utf-8")), encoding="utf-8")
        print(f"wrote {target}")
    else:
        print(render())
